# @package _global_
to_tensor:
  _target_: emg2qwerty.transforms.ToTensor
  fields: [emg_left, emg_right]

noise:
  _target_: emg2qwerty.transforms.AdditiveGaussianNoise
  scale: 0.04  # noise std = 4% of signal std

channel_dropout:
  _target_: emg2qwerty.transforms.ChannelDropout
  prob: 0.1   # drop each electrode channel with prob 0.1
  channel_dim: -1

gain_scaling:
  _target_: emg2qwerty.transforms.ChannelGainScaling
  max_scale: 0.2  # per-channel gain in [1 - max_scale, 1 + max_scale]
  channel_dim: -1

band_rotation:
  _target_: emg2qwerty.transforms.ForEach  # i.i.d rotation offset for each band
  transform:
    _target_: emg2qwerty.transforms.RandomBandRotation
    offsets: [-1, 0, 1]

temporal_jitter:
  _target_: emg2qwerty.transforms.TemporalAlignmentJitter
  max_offset: 120  # Max 60ms jitter for 2kHz EMG

logspec:
  _target_: emg2qwerty.transforms.LogSpectrogram
  n_fft: 64
  hop_length: 16  # Downsamples from 2kHz to 125Hz

specaug:
  _target_: emg2qwerty.transforms.SpecAugment
  n_time_masks: 3
  time_mask_param: 25  # Max 200ms per time mask for 125Hz spectrogram
  n_freq_masks: 2
  freq_mask_param: 4

transforms:
  train:
    - ${to_tensor}
    - ${noise}
    - ${band_rotation}
    - ${temporal_jitter}
    - ${logspec}
    - ${specaug}

  val:
    - ${to_tensor}
    - ${logspec}

  test: ${transforms.val}
